### ISSUE TITLE
Need better colorscheme

### ISSUE THREAD

**Issue by ketor** [coolceph/vimrc#7]
molokai is more likely to TextMate and Sublime, which is known as best gui editor on Mac.
So would we change default colorscheme to molokai?

**Comment by ketor** [comment]
The jellybeans has some compatibility issues with some terminals, and also is not compatible with the latest vim-airline.
I forced to use jellybeans for airline, and it looks bad.
But molokai is perfect in latest airline.

@yuandong1222

**Comment by ketor** [comment]
Molokai looks not perfect.
Maybe we need make a colorscheme by ourself.

**Comment by yuandong1222** [comment]
Is there a demo for molokai?

**Comment by ketor** [comment]
Get latest vimrc， and replace "colorscheme jellybeans" to "colorscheme molokai".
Restart vim, you will see molokai.

And airline now use "powerlineish", you can also set it to "molokai" too.

Another question is how to update submodules to their latest upstream repo?

**Comment by yuandong1222** [comment]
Maybe a shell script can do this, foreach bundle dir, do git pull?

On 9 February 2016 at 20:26, Ketor notifications@github.com wrote:

> Get latest vimrc， and replace "colorscheme jellybeans" to "colorscheme
> molokai".
> Restart vim, you will see molokai.
> 
> And airline now use "powerlineish", you can also set it to "molokai" too.
> 
> Another question is how to update submodules to their latest upstream repo?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/coolceph/vimrc/issues/7#issuecomment-181844590.

## 

Dong Yuan
Email:yuandong1222@gmail.com

**Comment by yuandong1222** [comment]
I tried molokai as you said, and what I got is ugly. But I am not sure whether I config right.

**Comment by ketor** [comment]
Look into the setup.sh.
Now setup.sh work without git submodules, and the repo can only contains a vimrc file and setup.sh, it's very very tiny.

I do git clone in function init_plugins(), git pull in function update_plugins() and make_tar in  function backup_vimrc().

**Comment by ketor** [comment]
After try a lot of colorschemes, I think jellybeans it the best one right now.
And we can use 'powerlineish' colorscheme for airline, so everything is ok.
