### ISSUE TITLE
Can we merge install.sh and setup.sh into one script?

### ISSUE THREAD

**Issue by yuandong1222** [coolceph/vimrc#8]
Then whether install or update, we can simply run the same script.

**Comment by ketor** [comment]
setup.sh now support install, update, make_tar.

Usage: setup.sh -i/-u/-b
-i -- install vimrc
-u -- update vimrc's plugins
-b -- backup ~/.vim

If we give up git submodules, we could use setup.sh only. 
All we really need in the repo is vimrc and setup.sh.

I looks into other vimrc repo, they install plugins use pathogen like setup.sh or use VBundle/NeoBundle.
So do you think we should upgrade our install method and give up submodules?

**Comment by yuandong1222** [comment]
why we can't run git submodules init & update everything?

**Comment by yuandong1222** [comment]
I am not familiar with VBundle/NeoBundle, so I have no idea.

**Comment by ketor** [comment]
VBundle/NeoBundle install plugin by git clone repo in ~/.vim/bundle, while pathogen do not provides this method.

If do not use submodules, our repo will be very simple and git submodules add more complexity for vimrc.

Also the ~/.vim dir don't be forced to as a repo dir, this will reduce the space occupied by vimrc.

That's what I think, to make everything more simple and easy to understand.

**Comment by ketor** [comment]
Update the setup.sh, now everything clean.

I ignored the problem of how to update vimrc itself. Use git repo in ~/.vim will make update easy.
