### ISSUE TITLE
Bug: Latest version has error when launch

### ISSUE THREAD

**Issue by yuandong1222** [coolceph/vimrc#9]
Error detected while processing VimEnter Auto commands for "*":
E492: Not an editor command: DisableWhitespace

**Comment by ketor** [comment]
stat ~/.vim/bundles/vim-better-whitespace
Need this plugin.

**Comment by ketor** [comment]
I add vim-better-whitespace in both setup.sh and git submodules.
So maybe something wrong with your git submodules.

Maybe you could try reinstall your vimrc by setup.sh again?
`cd $VIMRC_REPO_DIR;rm -rf ~/.vim;./setup.sh -i`

**Comment by yuandong1222** [comment]
I will try this later.

**Comment by ketor** [comment]
setup.sh updated to install as git submodule now, and also update is based on submodule now.

Try the new install method:
`bash -c "$( curl https://raw.githubusercontent.com/coolceph/vimrc/master/setup.sh )"`

**Comment by ketor** [comment]
@yuandong1222 Do your test the newest version?

**Comment by yuandong1222** [comment]
The setup.sh is amazing!!

While my first attempt failed since network issue, I should to fix it manually by git submodule update.

Here is the log:
子模组路径 'bundle/tagbar-phpctags.vim'：检出 '00d12a891482c35e6bd0dd9a8860163322a45daf'
正克隆到 'bundle/taghighlight'...
remote: Counting objects: 3195, done.
error: RPC failed; result=18, HTTP code = 200KiB/s
fatal: The remote end hung up unexpectedly
fatal: 过早的文件结束符（EOF）
fatal: index-pack failed
无法克隆 'https://github.com/abudden/taghighlight-automirror' 到子模组路径 'bundle/taghighlight'
All plugins init finished!
make: **\* 没有指明目标并且找不到 makefile。 停止。
Make vimproc.vim finished
Make vimrc finished

**Comment by yuandong1222** [comment]
I fix my setup by:
1) git submodule update
2) ./setup.sh -i

It works good to me. 

Thanks.
